---
locale: es
tags: []
layout: input_bottom
editor: 0
type: interactive
extra_visible: false
teacher_info: ''
manual_evaluation: false
choices: []
goal: !ruby/hash:ActiveSupport::HashWithIndifferentAccess
  kind: last_query_outputs
  output: "[[1, 2, 3], [4, 5, 6]]"
name: Juegos de azar
